version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: main

  - package-ecosystem: npm
    directory: /companion
    schedule:
      interval: weekly
    target-branch: main
    versioning-strategy: increase
    groups:
      development-tooling:
        dependency-type: development
